
-- 1 уровень категорий
INSERT INTO categories (name, parent_category_id) VALUES
('Копирайтинг', NULL),
('Интернет-магазины', NULL),
('Zero-coding', NULL),
('Webflow', NULL),
('WordPress', NULL),
('Vue', NULL),
('Дизайн сайтов', NULL),
('Доработка сайтов', NULL),
('Wap/PDA-сайты', NULL),
('Сайт «под ключ»', NULL),
('CMS (системы управления)', NULL),
('Продвижение сайта', NULL),
('1C Битрикс', NULL),
('Проектирование', NULL),
('SEO-оптимизация', NULL),
('Аудит сайта', NULL),
('Тильда', NULL),
('React', NULL),
('Менеджер проектов', NULL),
('Юзабилити-анализ', NULL),
('Флеш-сайты', NULL),
('QA (тестирование)', NULL),
('Лендинги', NULL),
('Laravel', NULL),
('OpenCart', NULL),
('MODx', NULL),
('Joomla', NULL),
('Magento', NULL),
('Node', NULL),
('Интеграция по API', NULL),
('Создание MVP', NULL),
('Yii', NULL),
('Редизайн сайтов', NULL),
('Пользовательские с…', NULL),
('Сайты', NULL);


